/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.arbolesdebusqueda;

import com.mycompany.arbolesdebusqueda.excepciones.ExcepcionOrdenInvalido;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author salet
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    String fecha;
    Integer prioridad;
    String tarea;
    public static int orden;
    ArbolBinarioBusqueda<FechaConPrioridad, String> arbol = new ArbolBinarioBusqueda<>();
    AVL<FechaConPrioridad, String> AVL = new AVL<>();
    ArbolMViasBusqueda arbolMVias;
    ArbolB arbolB;
    //IArbolBusqueda<FechaPrioridad,String> arbolgenerico=new IArbolBusqueda<>();

    public Agenda() throws ExcepcionOrdenInvalido {
        // Mostrar cuadro de diálogo para ingresar el número al iniciar el formulario
        var input = JOptionPane.showInputDialog(this, "Ingrese el orden para trabajar con el arbol MVias:");
        try {
            orden = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1); // Cerrar la aplicación si no se ingresa un número válido
        }
        System.out.println("esta entrando el orden " + orden);
        this.arbolMVias = new ArbolMViasBusqueda<>(orden);
        this.arbolB= new ArbolB<>(orden);

        initComponents();
        arbol.insertar(new FechaConPrioridad("2025-07-20", 2), "Defensa de proyecto de Grado");
        arbol.insertar(new FechaConPrioridad("2025-06-20", 2), "Presentacion Final de documentacion PG");
        arbol.insertar(new FechaConPrioridad("2024-09-21", 1), "Feria de emprendimiento");
        arbol.insertar(new FechaConPrioridad("2024-09-21", 2), "Anversario de la UE 9 de abril");
        arbol.insertar(new FechaConPrioridad("2025-06-20", 1), "Presentacion del juego con planificador");
        arbol.insertar(new FechaConPrioridad("2025-01-31", 1), "Viaje a Suiza");

        AVL.insertar(new FechaConPrioridad("2025-07-20", 2), "Defensa de proyecto de Grado");
        AVL.insertar(new FechaConPrioridad("2025-06-20", 2), "Presentacion Final de documentacion PG");
        AVL.insertar(new FechaConPrioridad("2024-09-21", 1), "Feria de emprendimiento");
        AVL.insertar(new FechaConPrioridad("2024-09-21", 2), "Anversario de la UE 9 de abril");
        AVL.insertar(new FechaConPrioridad("2025-06-20", 1), "Presentacion del juego con planificador");
        AVL.insertar(new FechaConPrioridad("2025-01-31", 1), "Viaje a Suiza");

        arbolMVias.insertarI(new FechaConPrioridad("2025-07-20", 2), "Defensa de proyecto de Grado");
        arbolMVias.insertarI(new FechaConPrioridad("2025-06-20", 2), "Presentacion Final de documentacion PG");
        arbolMVias.insertarI(new FechaConPrioridad("2024-09-21", 1), "Feria de emprendimiento");
        arbolMVias.insertarI(new FechaConPrioridad("2024-09-21", 2), "Anversario de la UE 9 de abril");
        arbolMVias.insertarI(new FechaConPrioridad("2025-06-20", 1), "Presentacion del juego con planificador");
        arbolMVias.insertarI(new FechaConPrioridad("2025-01-31", 1), "Viaje a Suiza");

        arbolB.insertar(new FechaConPrioridad("2025-07-20", 2), "Defensa de proyecto de Grado");
        arbolB.insertar(new FechaConPrioridad("2025-06-20", 2), "Presentacion Final de documentacion PG");
        arbolB.insertar(new FechaConPrioridad("2024-09-21", 1), "Feria de emprendimiento");
        arbolB.insertar(new FechaConPrioridad("2024-09-21", 2), "Anversario de la UE 9 de abril");
        arbolB.insertar(new FechaConPrioridad("2025-06-20", 1), "Presentacion del juego con planificador");
        arbolB.insertar(new FechaConPrioridad("2025-01-31", 1), "Viaje a Suiza");
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agenda tu tarea");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 102, 204));
        jRadioButton1.setText("ABB");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 102, 204));
        jRadioButton2.setText("AVL");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 102, 204));
        jRadioButton3.setText("AMV");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 102, 204));
        jRadioButton4.setText("AB");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(jRadioButton3)
                .addGap(71, 71, 71)
                .addComponent(jRadioButton4)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(225, 225, 225));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(225, 225, 225));
        jButton1.setText("buscar tareas");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ingrese las tareas o actividades a realizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "YYYY-MM-DD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(225, 225, 225));
        jButton2.setText("Agregar tarea");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1-10", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar tarea");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Fecha de presentacion");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Nivel de prioridad");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Tarea");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jTextField3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jButton2)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jMenu2.setText("Recorridos");
        jMenu2.setFocusable(false);
        jMenu2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem1.setText("PorNiveles");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setText("In-Orden");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem3.setText("Pre-Orden");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem4.setText("Post-Orden");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fecha = jTextField3.getText();
        prioridad = Integer.parseInt(jTextField4.getText());
        String tareaBuscada = null;
        if (jRadioButton1.isSelected()) {
            tareaBuscada = arbol.buscar(new FechaConPrioridad(fecha, prioridad));
        }
        if (jRadioButton2.isSelected()) {
            tareaBuscada = AVL.buscar(new FechaConPrioridad(fecha, prioridad));
        }
        if (jRadioButton3.isSelected()) {
            tareaBuscada = (String) arbolMVias.buscar(new FechaConPrioridad(fecha, prioridad));
        }
        if (jRadioButton4.isSelected()) {
            tareaBuscada = (String) arbolB.buscar(new FechaConPrioridad(fecha, prioridad));
        }
        jTextArea1.setText(tareaBuscada);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fecha = jTextField3.getText();
        prioridad = Integer.parseInt(jTextField4.getText());
        tarea = jTextField2.getText();
        if (!fecha.isEmpty() && prioridad != null && !tarea.isEmpty()) {
            arbol.insertar(new FechaConPrioridad(fecha, prioridad), tarea);
            AVL.insertar(new FechaConPrioridad(fecha, prioridad), tarea);
            arbolMVias.insertarI(new FechaConPrioridad(fecha, prioridad), tarea);
            arbolB.insertar(new FechaConPrioridad(fecha, prioridad), tarea);
            String tarea = arbol.buscar(new FechaConPrioridad(fecha, prioridad));
            jTextArea1.setText("tarea agregada en fecha: " + fecha + " con prioridad: " + prioridad + ". \n" + "- " + tarea);
        } else {
            //throw new IllegalArgumentException("DATOS NO COMPLETOS");
            JOptionPane.showMessageDialog(this, "Por favor complete los campos de 'fecha', 'prioridad' y 'tarea'", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fecha = jTextField3.getText();
        prioridad = Integer.parseInt(jTextField4.getText());
        if (!fecha.isEmpty() && prioridad != null) {
            tarea = arbol.buscar(new FechaConPrioridad(fecha, prioridad));
            arbol.eliminar(new FechaConPrioridad(fecha, prioridad));
            AVL.eliminar(new FechaConPrioridad(fecha, prioridad));
            arbolMVias.eliminar(new FechaConPrioridad(fecha, prioridad));
            arbolB.eliminar(new FechaConPrioridad(fecha, prioridad));
            jTextArea1.setText("tarea eliminada de fecha: " + fecha + " con prioridad: " + prioridad + ". \n" + "- " + tarea);
            //que se muestre la fecha, la prioridad y la tarea insertada en el textArea
        } else {
            JOptionPane.showMessageDialog(this, "Por favor complete los campos de 'fecha', 'prioridad' y 'tarea'", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        //me muestra todas las tareas que tengo en el arbol en el recorrido por niveles para visualizar el arbol
        List<FechaConPrioridad> listaElementos = arbol.recorridoEnInOrden();
        //de lista a cadena de texto
        StringBuilder textoLista = new StringBuilder();
        for (FechaConPrioridad elemento : listaElementos) {
            tarea = arbol.buscar(elemento);
            textoLista.append(elemento + "Tarea: " + "\n" + "   " + tarea + "\n").append("\n");
        }
        jTextArea1.setText(textoLista.toString());
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        List<FechaConPrioridad> listaElementos = arbolMVias.recorridoEnInOrden();
        //de lista a cadena de texto
        StringBuilder textoLista = new StringBuilder();
        for (FechaConPrioridad elemento : listaElementos) {
            tarea = (String) arbolMVias.buscar(elemento);
            textoLista.append(elemento + "Tarea: " + "\n" + "   " + tarea + "\n").append("\n");
        }
        jTextArea1.setText(textoLista.toString());
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        List<FechaConPrioridad> listaElementos = AVL.recorridoEnInOrden();
        //de lista a cadena de texto
        StringBuilder textoLista = new StringBuilder();
        for (FechaConPrioridad elemento : listaElementos) {
            tarea = AVL.buscar(elemento);
            textoLista.append(elemento + "Tarea: " + "\n" + "   " + tarea + "\n").append("\n");
        }
        jTextArea1.setText(textoLista.toString());
        jRadioButton1.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (jRadioButton1.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbol.recorridoPorNiveles();
            //de lista a cadena de texto
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n"); // Agrega cada elemento seguido de un salto de línea
            }
            jTextArea1.setText(textoLista.toString());
        }
        if (jRadioButton2.isSelected()) {
            List<FechaConPrioridad> listaElementos = AVL.recorridoPorNiveles();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
        //falta del arbol MVias y del arbol B los recorridos por niveles
        if (jRadioButton3.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbolMVias.recorridoPorNiveles();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
        if (jRadioButton4.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbolB.recorridoPorNiveles();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (jRadioButton1.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbol.recorridoEnInOrden();
            //de lista a cadena de texto
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n"); // Agrega cada elemento seguido de un salto de línea
            }
            jTextArea1.setText(textoLista.toString());
        }
        if (jRadioButton2.isSelected()) {
            List<FechaConPrioridad> listaElementos = AVL.recorridoEnInOrden();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
        //falta del arbol MVias y del arbol B los recorridos por niveles
        if (jRadioButton3.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbolMVias.recorridoEnInOrden();
            //de lista a cadena de texto
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n"); // Agrega cada elemento seguido de un salto de línea
            }
            jTextArea1.setText(textoLista.toString());
        }
        if (jRadioButton4.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbolB.recorridoEnInOrden();
            //de lista a cadena de texto
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n"); // Agrega cada elemento seguido de un salto de línea
            }
            jTextArea1.setText(textoLista.toString());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (jRadioButton1.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbol.recorridoEnPreOrden();
            //de lista a cadena de texto
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n"); // Agrega cada elemento seguido de un salto de línea
            }
            jTextArea1.setText(textoLista.toString());
        }
        if (jRadioButton2.isSelected()) {
            List<FechaConPrioridad> listaElementos = AVL.recorridoEnPreOrden();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
        //falta del arbol MVias y del arbol B los recorridos por niveles
        if (jRadioButton3.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbolMVias.recorridoEnPreOrden();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
        if (jRadioButton4.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbolB.recorridoEnPreOrden();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (jRadioButton1.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbol.recorridoEnPostOrden();
            //de lista a cadena de texto
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n"); // Agrega cada elemento seguido de un salto de línea
            }
            jTextArea1.setText(textoLista.toString());
        }
        if (jRadioButton2.isSelected()) {
            List<FechaConPrioridad> listaElementos = AVL.recorridoEnPostOrden();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
        //falta del arbol MVias y del arbol B los recorridos por niveles
        if (jRadioButton3.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbolMVias.recorridoEnPostOrden();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
        if (jRadioButton4.isSelected()) {
            List<FechaConPrioridad> listaElementos = arbolB.recorridoEnPostOrden();
            StringBuilder textoLista = new StringBuilder();
            for (FechaConPrioridad elemento : listaElementos) {
                textoLista.append(elemento).append("\n");
            }
            jTextArea1.setText(textoLista.toString());
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        List<FechaConPrioridad> listaElementos = arbolB.recorridoEnInOrden();
        //de lista a cadena de texto
        StringBuilder textoLista = new StringBuilder();
        for (FechaConPrioridad elemento : listaElementos) {
            tarea=(String) arbolB.buscar(elemento);
            textoLista.append(elemento + "Tarea: " + "\n" + "   " + tarea + "\n").append("\n");
        }
        jTextArea1.setText(textoLista.toString());
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ExcepcionOrdenInvalido {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Agenda().setVisible(true);
                } catch (ExcepcionOrdenInvalido ex) {
                    Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
